name: sprint-challenge
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - flask=*
  - jinja2=*
  - flask-sqlalchemy=*
  - tweepy=*
  - spacy=*
  - python-dotenv=*
  - spacy-model-en_core_web_sm=*